name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
        with:
            toolchain: nightly
            override: true
            components: rustfmt
      - name: Rustfmt
        run: cargo fmt -- --check

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
        with:
            toolchain: nightly
            override: true
            components: clippy
      - name: Build
        run: cargo build --verbose
      - name: Clippy
        run: cargo clippy -- -D warnings
      - name: Run tests
        run: cargo test --verbose
